modLoader="javafml"
loaderVersion="[35,)"
license="MIT"
issueTrackerURL="https://github.com/EwyBoy/Quick-Harvest/issues"

[[mods]]
modId="quickharvest"
displayName="Quick Harvest"
version="${file.jarVersion}"
authors="Ewy, LuHeGi"
credits="All credits goes to LuHeGi for being a good boy"
description='''
Quick Harvest any crop or plant by right-clicking
'''

[[dependencies.quickharvest]]
    modId="forge"
    mandatory=true
    versionRange="35.1.4-35.2"
    ordering="AFTER"
    side="BOTH"

[[dependencies.quickharvest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
