modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/EwyBoy/Quick-Harvest/issues"

[[mods]]
modId="quickharvest"
displayName="Quick Harvest"
version="${file.jarVersion}"
authors="Ewy, LuHeGi"
credits="All credits goes to LuHeGi for being a good boy"
description="Quick Harvest any crop or plant by right-clicking"

[[dependencies.quickharvest]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.18,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.quickharvest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2, 1.19]"
    ordering="NONE"
    side="BOTH"
