modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/EwyBoy/Quick-Harvest/issues"

[[mods]]
modId="quickharvest"
displayName="Quick Harvest"
version="${file.jarVersion}"
authors="Ewy, LuHeGi"
credits=""
description='''
Quick Harvest any crop or plant by right-clicking
'''

[[dependencies.quickharvest]]
    modId="forge"
    mandatory=true
    versionRange="[30.0.41,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.quickharvest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"