modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/EwyBoy/Cultivated-Tech/issues"

[[mods]]
modId="quickharvest"
displayName="Quick Harvest"
version="${file.jarVersion}"
authors="Ewy"
credits=""
description='''
Harvest crops by right-clicking
'''

[[dependencies.quickharvest]]
    modId="forge"
    mandatory=true
    versionRange="[28.1.61,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.quickharvest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"